### ISSUE TITLE
Build fails with gcc-15 (Fedora 42)

### ISSUE THREAD

**Issue by junghans** [lanl/MPI-Bash#20]
From https://bugzilla.redhat.com/show_bug.cgi?id=2340885:
```
Making all in src
make[1]: Entering directory '/builddir/build/BUILD/mpibash-1.4-build/mpibash-1.4/openmpi/src'
/bin/sh ../libtool  --tag=CC   --mode=compile mpicc -DPACKAGE_NAME=\"mpibash\" -DPACKAGE_TARNAME=\"mpibash\" -DPACKAGE_VERSION=\"1.4\" -DPACKAGE_STRING=\"mpibash\ 1.4\" -DPACKAGE_BUGREPORT=\"pakin@lanl.gov\" -DPACKAGE_URL=\"\" -DPACKAGE=\"mpibash\" -DVERSION=\"1.4\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CONFIG_H=1 -DHAVE_BUILTINS_H=1 -DHAVE_PATHNAMES_H=1 -DHAVE_SHELL_H=1 -DHAVE_BASHGETOPT_H=1 -DHAVE_EXECUTE_CMD_H=1 -I. -I../../src  -DSHELL -I/usr/include/bash -I/usr/include/bash/include -I/usr/include/bash/builtins   -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  -c -o mpibash_la-util.lo `test -f 'util.c' || echo '../../src/'`util.c
libtool: compile:  mpicc -DPACKAGE_NAME=\"mpibash\" -DPACKAGE_TARNAME=\"mpibash\" -DPACKAGE_VERSION=\"1.4\" "-DPACKAGE_STRING=\"mpibash 1.4\"" -DPACKAGE_BUGREPORT=\"pakin@lanl.gov\" -DPACKAGE_URL=\"\" -DPACKAGE=\"mpibash\" -DVERSION=\"1.4\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_CONFIG_H=1 -DHAVE_BUILTINS_H=1 -DHAVE_PATHNAMES_H=1 -DHAVE_SHELL_H=1 -DHAVE_BASHGETOPT_H=1 -DHAVE_EXECUTE_CMD_H=1 -I. -I../../src -DSHELL -I/usr/include/bash -I/usr/include/bash/include -I/usr/include/bash/builtins -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -c ../../src/util.c  -fPIC -DPIC -o .libs/mpibash_la-util.o
make[1]: Leaving directory '/builddir/build/BUILD/mpibash-1.4-build/mpibash-1.4/openmpi/src'
In file included from /usr/include/bash/builtins.h:34,
                 from ../../src/mpibash.h:10,
                 from ../../src/util.c:8:
../../src/util.c: In function ‘mpibash_invoke_bash_command’:
/usr/include/bash/general.h:148:33: error: too many arguments to function ‘list_reverse’; expected 0, have 1
  148 |   ((list && list->next) ? (type)list_reverse ((GENERIC_LIST *)list) \
      |                                 ^~~~~~~~~~~~
../../src/util.c:80:14: note: in expansion of macro ‘REVERSE_LIST’
   80 |   arg_list = REVERSE_LIST(arg_list, WORD_LIST *);
      |              ^~~~~~~~~~~~
In file included from /usr/include/bash/shell.h:42,
                 from ../../src/mpibash.h:11:
/usr/include/bash/externs.h:155:22: note: declared here
  155 | extern GENERIC_LIST *list_reverse ();
      |                      ^~~~~~~~~~~~
make[1]: *** [Makefile:552: mpibash_la-util.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Entering directory '/builddir/build/BUILD/mpibash-1.4-build/mpibash-1.4/openmpi/src'
```

This is with 5.2.37.

**Comment by spakin** [comment]
I have not yet been able to reproduce this locally with a source build (i.e., non-RPM).  Can you?

This is with RHEL 8.10 on aarch64, Bash 5.2.37 (installed from source), GCC 8.5.0, and Open MPI 3.1.6.

**Comment by junghans** [comment]
Sorry for the delay here you go:
https://github.com/junghans/mpibash.spec/actions/runs/16891155736/job/47850999186
it is with this workflow:
```yaml
name: CI
on:
  push:
    branches:
      - github

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:rawhide
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build fedpkg
        run: sudo dnf -y install fedpkg
      - name: Make SRPM
        run: |
          spectool -g mpibash.spec
          fedpkg srpm
      - name: Install deps
        run: sudo dnf -y builddep mpibash.spec
      - name: Build rpm
        run: fedpkg local
```
